site_name: Luna SDK Docs
site_url: https://www.lunasdk.org/
theme: readthedocs

nav:
    - Home: index.md
    - Manual: 
        - Introduction:
            - Introduction: manual/introduction/index.md
            - Getting Started: manual/introduction/getting_started/index.md
        - Basics:
            - Basics: manual/basics/index.md
            - Coding Convention: manual/basics/coding_convention.md
            - Initialization and Shutdown: manual/basics/initialization_and_shutdown.md
            - Basic Types: manual/basics/basic_types.md
            - Strings: manual/basics/strings.md
            - Memory Management: manual/basics/memory_management.md
            - Modules: manual/basics/modules.md
            - Variant: manual/basics/variant.md