site_name: Luna SDK Docs
site_url: https://www.lunasdk.org/
theme: readthedocs

nav:
    - Home: index.md
    - Manual: 
        - Introduction:
            - Introduction: manual/introduction/index.md
            - Getting Started: manual/introduction/getting_started/index.md
        - Fundamental:
            - Fundamental: manual/fundamental/index.md
        - Modules:
            - Rendering: manual/rendering/index.md