site_name: Luna SDK Docs
site_url: https://www.lunasdk.org/
theme: readthedocs
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
    - mdx_math:
        enable_dollar_delimiter: true
nav:
    - Home: index.md
    - License: license.md
    - Manual: 
        - Introduction:
            - Introduction: manual/introduction/index.md
            - Getting Started: manual/introduction/getting_started/index.md
        - Basics:
            - Basics: manual/basics/index.md
            - Coding Convention: manual/basics/coding_convention.md
            - Initialization and Shutdown: manual/basics/initialization_and_shutdown.md
            - Basic Types: manual/basics/basic_types.md
            - Strings: manual/basics/strings.md
            - Memory Management: manual/basics/memory_management.md
            - Modules: manual/basics/modules.md
            - Variants: manual/basics/variants.md
            - Type System: manual/basics/type_system.md
            - Serialization and Deserialization: manual/basics/serialization_and_deserialization.md
            - Boxed Objects: manual/basics/boxed_objects.md
            - Interfaces: manual/basics/interfaces.md
            - Error Handling: manual/basics/error_handling.md
            - Assertions: manual/basics/assertions.md
            - File Management: manual/basics/file_management.md
            - Thread and Synchronization Objects: manual/basics/thread_and_synchronization_objects.md
            - Time: manual/basics/time.md
            - Logs: manual/basics/logs.md
            - Math Library: manual/basics/math_library.md
        - RHI:
            - RHI: manual/rhi/index.md
            - Devices: manual/rhi/devices.md
            - Command Queues and Command Buffers: manual/rhi/command_queues_and_command_buffers.md
            - Resources: manual/rhi/resources.md
            - Pipeline Configuration: manual/rhi/pipeline_configuration.md
            - Recording Commands: manual/rhi/recording_commands.md
            - Shader Resource Binding: manual/rhi/shader_resource_binding.md
    - Programming Reference:
        - Runtime: api/runtime.md